#!/bin/bash

set -vx

wmctrl -s 1
ssh -l mdomail  -o stricthostkeychecking=no 0 "export DISPLAY=:0.0; thunderbird" &
sleep 2

wmctrl -s 2
ssh -l b1       -o stricthostkeychecking=no 0 "export DISPLAY=:0.0; /opt/google/chrome/google-chrome wsj.com" &
sleep 2

wmctrl -s 3
ssh -l b2       -o stricthostkeychecking=no 0 "export DISPLAY=:0.0; /opt/google/chrome/google-chrome" &
sleep 2

wmctrl -s 4
ssh -l facebook -o stricthostkeychecking=no 0 "export DISPLAY=:0.0; /opt/google/chrome/google-chrome" &
sleep 2

wmctrl -s 5
ssh -l youtube  -o stricthostkeychecking=no 0 "export DISPLAY=:0.0; /opt/google/chrome/google-chrome" &
sleep 2

wmctrl -s 1

exit
